Building DAG of jobs...
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	10	cluster_inserts
	10	extract_inserts_from_fq
	21

rule extract_inserts_from_fq:
    input: /DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/data/pDNA_insert_seq_2/raw/fastq_files/6382_4_TF_lib_oligos_TTATAACC-AGCGCTAG_S4_R1_001.fastq.gz
    output: results/6382_4_TF_lib_oligos_TTATAACC-AGCGCTAG_S4_barcodes.tsv
    log: /DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/pDNA_insert_seq/analysis_gcf6382/log/extract_inserts_from_fq.log
    jobid: 14
    wildcards: ecn=6382_4_TF_lib_oligos_TTATAACC-AGCGCTAG_S4

Terminating processes on user request.
Error in rule extract_inserts_from_fq:
    jobid: 14
    output: results/6382_4_TF_lib_oligos_TTATAACC-AGCGCTAG_S4_barcodes.tsv
    log: /DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/pDNA_insert_seq/analysis_gcf6382/log/extract_inserts_from_fq.log

RuleException:
CalledProcessError in line 30 of /DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/pDNA_insert_seq/analysis_gcf6382/Snakefile:
Command ' set -euo pipefail;  /DATA/usr/m.trauernicht/software/miniconda3/envs/tf-activity/bin/python /DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/pDNA_insert_seq/analysis_gcf6382/.snakemake.j3nnc9dw.mt20201026_insert-counts.py ' returned non-zero exit status 1.
  File "/DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/pDNA_insert_seq/analysis_gcf6382/Snakefile", line 30, in __rule_extract_inserts_from_fq
  File "/DATA/usr/m.trauernicht/software/miniconda3/envs/tf-activity/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job extract_inserts_from_fq since they might be corrupted:
results/6382_4_TF_lib_oligos_TTATAACC-AGCGCTAG_S4_barcodes.tsv
Complete log: /DATA/usr/m.trauernicht/projects/SuRE_deep_scan_trp53_gr/pDNA_insert_seq/analysis_gcf6382/.snakemake/log/2021-03-18T132710.035027.snakemake.log
